spring.application.name=Edu
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/edu-space?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Import secret properties for local development (this file will be ignored by Git)
spring.config.import=optional:classpath:application-secret.properties

# Connection pool settings for remote DB
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.frontend.url=${FRONTEND_URL:http://localhost:5173}

# Gemini AI Configuration (Secrets are loaded from application-secret.properties or ENV vars)
gemini.api.key1=${GEMINI_KEY_1:}
gemini.api.key2=${GEMINI_KEY_2:}
gemini.api.key3=${GEMINI_KEY_3:}

#gemini.api.keys=${GEMINI_KEY_1:},${GEMINI_KEY_2:},${GEMINI_KEY_3:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

# GMAIL SMTP
email.address=${EMAIL_ADDRESS:hieumastermind@gmail.com}
email.password=${EMAIL_PASSWORD:}

# GOOGLE OAUTH
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:217594244925-ktlmobo9tud4u6mfas4mof87a3e1v504.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile
